### ISSUE TITLE
Quick Start - Install and Configure?

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat.org#117]
I think a main thing that is missing in the xCAT "quick start" is the fact that it's not easy to quickly start using xCAT.  There's no way we can cover everything in a quick start guide... if we really want something to be quick.... 

So what is the mininum set required to have the user essentially try and play with xCAT 

## Use Case: 

As a xCAT potential user, I want to be able to quickly install/configure xCAT and try something out

Here's some thoughts of the lifecycle pieces that may be required...

### Scope (Assumptions)
* Focus on Power AC922 Servers
* Assume that the Administrator has installed a copy of Fedora or RHEL

### Install xCAT
- [ ] Does `go-xcat` make this essentially a one step process? 
- [ ] Any advantage of doing a `docker pull` to avoid the install step? 

### Configure xCAT 
* Assumption: 2 VLAN network: 1 for Compute/OS, 1 for BMC (mgmt)
   * networks must be a private subnet (192.168.X.X or 172.10.X.X or 10.X.X.X)
- [ ] Change xCAT to default to some domain?  server.net or clusters.net or some generic? 
- [ ] What else is needed? or can work out of the box? 

### Discover Node 
* set up an open range
- [ ] Can we ship a pre-configured node definition inside xCAT? 
* what kind of discovery  do we want to cover? MTMS only? Or switch based? 
   * switch based would require us to be able to communicate with the switch...  maybe complicating the  "quick start" goal
### Configure an OS 
* Copycds 

### Deploy an OS 
* Deploy the configured OS

**Comment by gurevichmark** [comment]
Some thoughts:
* Display all the node templates with `lsdef -t node --template` and get more details about each template with `lsdef -t node --template <template name>`. For example `lsdef -t node --template ppc64le-template`
* We have this section, but it involves "inventory": https://xcat-docs.readthedocs.io/en/stable/advanced/xcat-inventory/define_create_cluster.html

**Comment by zet809** [comment]
hi, @whowutwut and @gurevichmark , any updates for this task? We want to have at least 1 user scenario quickstart document available by the end of next week, then we can publish the 1st new home page. What is your idea? Thx!

**Comment by whowutwut** [comment]
@zet809 I don't think we are looking at this right now, so will remove the assignments.  I don't necessarily think we need to block the publish of the homepage because of this. I thought the 2nd home page is already active for some time now...
