### ISSUE TITLE
confignics 

### ISSUE THREAD

**Issue by ChristopherWalker** [xcat2/xcat.org#134]
https://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/network/cfg_second_adapter.html

This page points out that confignics is deprecated. It would be useful if it pointed to the new version (which I think is confignetwork).

**Comment by zet809** [comment]
Thank you very much for point this out, @ChristopherWalker 

Hi, @bybai , will you pls help to correct our document mentioned above? Thx!

**Comment by robin2008** [comment]
@zet809   help to transfer this ticket to `xcat-core` repo.

**Comment by zet809** [comment]
hi, @ChristopherWalker , thanks very much for point this out, I have move this issue to https://github.com/xcat2/xcat-core/issues/6057 to update the document. 
Thanks again.
