### ISSUE TITLE
Figure out the end to end for updating go-xcat script on xcat.org

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat.org#19]
This issue is open to come up with the end to end design of the `go-xcat` script.   Really, we should not release this function if we do not have a complete end to end in place or at least thought on how we will maintain this script updates automatically. 
- How do we update it on each release? The source is in the xcat-core repository
- Why do we put it in http://xcat.org/files/go-xcat  <-  There is no version control here.  Do we always just replace with the latest?  
- What releases do we support for go-xcat, can install any release? 

We cannot have this be manually copied each release.  That is not acceptable if we want to release consistently and quickly without missing any steps.

**Comment by daniceexi** [comment]
Following are my thoughts about go-xcat:

* go-xcat is a general tool and it should be stable after several version of evolution. Ideally, when it gets to stable we don't need to touch it if no issue found. Base on this thought, I don't think we need to deliver go-xcat with xCAT release.
* go-xcat has a version number, we only need to update this number when we made a change against it. That means go-xcat could be totally separated with xCAT release.
* it would be great if we can automatically ship this script. One thought is put in xcat.org repository.

**Comment by whowutwut** [comment]
Should we move the `go-xcat` script into the xcat.org repsitory?

**Comment by whowutwut** [comment]
No longer need this as we are pointing to the GitHub for downloading go-xcat. 
I'd like to remove `go-xcat` script from xcat.org/files, and close this out,  Does that sound good @neo954 ?
