### ISSUE TITLE
Enhance the cleanup script to leave around the last snapshot build

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat.org#22]
Enhance the cleanup script to leave the last snapshot build , regardless of how old it is.  

I just thought about a scenario that is not covered by the cleanup script added in PR #21 so will not enable the cron job until this is satisfied. 

For example, if xCAT team currently maintains 2.11, 2.12 and 2.13 release. 

There is not much activity on 2.11 but it's in service mode and we will fix bugs that are reported that are critical.    An issue comes in and we fix it in master and decide it should be cherry picked back to 2.13, 2.12, and 2.12.  But there is no GA planned for 2.11 release at this time.   Once we commit the code to 2.11 branch, it automatically builds a snapshot in the daily build and is uploaded to xcat.org download site. 

Since we don't have any GA plans, after 30 days, the snapshot build will be deleted. We want to keep around at least that last snap build so that users could decide to pick up the snapshot containing the fix, even if xCAT team does not do a 2.11.x GA release.

**Comment by whowutwut** [comment]
@zet809 This was merged but  I'm not confident that this will work without any issues.  What's the thought here... should we enable this as a cronjob or should we manually clean it up.  We have backup of xcat.org , so we can UT it on those backups first.

**Comment by zet809** [comment]
From my point of view, keep the latest 7 snap-shot build(one week I mean) is enough, or at most keep the build for a release. For example, we have released 2.14.1, we don't want anyone switch back to 2.14.1 snap-shot build since it is out-of-service. 
So, for your PR, keep 30 days is OK for me.

**Comment by whowutwut** [comment]
We did in the past release BETA code, so we had symlinks that tracked those. 
Removing the BETA code would break the "readme" documentation that we passed to folks...

**Comment by gurevichmark** [comment]
Issue moved to [xcat2/xcat2.github.io #47](https://github.com/xcat2/xcat2.github.io/issues/47) via [**ZenHub**](https://www.zenhub.com/)
