### ISSUE TITLE
Sync up the news sidebars between xcat.org and github

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat.org#27]
I'm not sure if this is possible but today we have two locations where we need to maintain a xcat news. 

1) http://xcat.org/
2) https://github.com/xcat2/xcat-core/wiki

Opening this task to see if there's a good way that xcat.org could link to that sidebar, or even just remove it completely and provide a link to the github wiki. 

It's not good to have two places holding the same information.

**Comment by gurevichmark** [comment]
Issue moved to [xcat2/xcat2.github.io #48](https://github.com/xcat2/xcat2.github.io/issues/48) via [**ZenHub**](https://www.zenhub.com/)
