### ISSUE TITLE
xCAT 2.12.3 release checklist

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat.org#34]
Opening this issue to track the required things that need to be done in preparation for the xCAT 2.12.3 release. This list can be duplicated in subsequent releases so that we have a process to follow to ensure that the release results are consistent. 

Please reference this issue on any pull request or modify this description box with the pull request number to keep the links

- Create and update the xCAT release notes 

   https://github.com/xcat2/xcat-core/wiki/XCAT_2.12.3_Release_Notes

- Modify the xCAT release page in RTD [**Done**: https://github.com/xcat2/xcat-core/commit/9f65c0f001c92905831fbdf63cd68d61c689aeb5 ]

   https://github.com/xcat2/xcat-core/blob/master/docs/source/overview/xcat2_release.rst

  _Requires merge of master -> 2.12_  [https://github.com/xcat2/xcat-core/pull/1929]
- Update the xcat-core Wiki page and include the sidebar link to the release notes [**Done**: @pdlun92 ]

- Update the xcat.org pages [**Done**:  Pull Request: https://github.com/xcat2/xcat.org/pull/35]
   - index.html
   - download.html 

   _Requires merge of master -> stable_ , then pull on xcat.org. [https://github.com/xcat2/xcat.org/pull/36]

* promote the 2.12.3 build on xcat.org server

* Create a release and tag for the 2.12.3 in GitHub 

* Activate the RTD build for the 2.12.3 release 

* bump up the xCAT Version in the master branch to 2.12.4

* Update go-xcat script over in xcat.org

**Comment by whowutwut** [comment]
If anyone thinks of anything else that is required, please comment here.

**Comment by daniceexi** [comment]
@whowutwut 

Three more things:

1. create a tag for the 2.12.3
2. bump up the xCAT Version in the master branch to 2.12.4
3. make sure the go-xcat in xcat.org has been updated with latest one

**Comment by whowutwut** [comment]
Thanks @daniceexi  I've updated those into the list above.

**Comment by whowutwut** [comment]
Closing out this issue as we've completed the tasks outlined

**Comment by tingtli** [comment]
@whowutwut  Follow your steps, here is  my comments
1.promote the 2.12.3 build on xcat.org server. Need to run "./promote_build.py --type=snap 2.12.4 --link_latest --force"  on xcat.org
2. Need to copy xcat-dep-201611092219.tar.bz2 to xcat-dep-2.12.4-linux.tar.bz2 on xcat.org (i didn't find the script to do that, so i just copy it)

**Comment by whowutwut** [comment]
@tingtli  Yes, we should probably create another issue for each release so we can update steps if needed.  

For 1) I think the `--force` option should only be needed if we promoted multiple times.  If we are running it the first time, we should not need it. 

For 2) I think you are right, we have to manually create that symlink...
