### ISSUE TITLE
xCAT 2.13 Release Checklist

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat.org#39]
Opening this issue to track the required things that need to be done in preparation for the xCAT 2.13 release. This list can be duplicated in subsequent releases so that we have a process to follow to ensure that the release results are consistent. 

_Please reference this issue on any pull request or modify this description box with the pull request number to keep the links_

## Preparation

- Create and update the xCAT release notes [**Done**, need to team to fill in]
   https://github.com/xcat2/xcat-core/wiki/XCAT_2.13_Release_Notes

- Modify the xCAT release page in RTD   http://xcat-docs.readthedocs.io/en/2.13.0/overview/xcat2_release.html

- Update the xcat.org pages, Pull Request:  https://github.com/xcat2/xcat.org/pull/40 [**DONE - merged**]
  - index.html
  - download.html 

- Update `go-xcat` script over in xcat.org [**Done**]
  This is no longer needed, will reference go-xcat directly from a repo #41 

## Day of Release 
- Update the xcat-core Wiki page and include the sidebar link to the release notes 
- Create a release and tag for the 2.13.0 in GitHub 
-  merge master -> stable , then `git pull` on xcat.org server 
- Once the RC build has been blessed, run the promote_build script on xcat.org for 2.13. 
   Manually symlink for xcat-deps
- Activate the RTD build for the 2.13.0 release 
- bump up the xCAT Version in the master branch to 2.13.1

**Comment by whowutwut** [comment]
I just ran the promote script on xcat.org for 2.13 release, @zet809  Can the team start validating the repos: 

- Linux 2.13 repo
- Linux latest repo
- Ubuntu 2.13 repo
- Ubuntu latest repo

**Comment by whowutwut** [comment]
I think the release tasks are complete, except for editing the Release Notes.

**Comment by zet809** [comment]
@whowutwut I have updated the Release Notes, So close this defect and xCAT 2.13 is released. Thx!
