### ISSUE TITLE
xCAT 2.13.4 release checklist

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat.org#59]
Opening this issue to track the required things that need to be done in preparation for the xCAT 2.13.4 release. 

## Preparation

- Update the xCAT release notes [**Done**]
   https://github.com/xcat2/xcat-core/wiki/XCAT_2.13.4_Release_Notes

- Modify the xCAT release page in RTD   http://xcat-docs.readthedocs.io/en/2.13.4/overview/xcat2_release.html [**Done**]

## Day of Release [****]
- Update the xcat-core Wiki page and include the sidebar link to the release notes [Done]
- Create a release and tag for the 2.13.4 in GitHub  [Done]
- Update the xcat.org pages
    - merge master -> stable , then `git pull` on xcat.org server [Done](https://github.com/xcat2/xcat.org/pull/62)
    - Once the RC build has been blessed, run the promote_build script on xcat.org for 2.13.4[Done]
```
xcat@sense:/var/www/xcat.org/files/xcat/xcat-dep/2.x_Ubuntu$ ln -s xcat-dep-ubuntu-201702211344.tar.bz2 xcat-dep-2.13.4-ubuntu.tar.bz2
xcat@sense:/var/www/xcat.org/files/xcat/xcat-dep/2.x_Linux$ln -s xcat-dep-201702211334.tar.bz2 xcat-dep-2.13.4-linux.tar.bz2
```
- Activate the RTD build for the 2.13.4 release [Done]
  Updated the badge in https://github.com/xcat2/xcat-core/blob/master/README.rst
- bump up the xCAT Version in the master branch to 2.13.5 [Done]

**Comment by zet809** [comment]
hi, @hu-weihua , all the items in the checklist had been finished. Pls help to review and verify. Thx!

**Comment by tingtli** [comment]
@hu-weihua i think we should close this bug and open a new bug for xCAT 2.13.5 release and reference to #3325 in that bug.
