### ISSUE TITLE
Upload/document a devel version of xCAT-genesis-base to xcat.org 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat.org#60]
@zet809  Open this issue to track the work...  Like we discussed on the interlock meeting, I agree that we should put the xCAT-genesis-base based on a beta version of Fedora26 onto xcat.org.  

Suggest the following path, I created a beta directory here:
```
/var/www/xcat.org/files/xcat/xcat-dep/2.x_Linux/beta
```

Then we should create some README with steps for users that want to try out hardware discovery. Or we just leave this for our internal teams , since this will only be used internally.

**Comment by whowutwut** [comment]
How about here @zet809 : https://github.ibm.com/xcat2/team_process/blob/master/CS17A/p9_hardware_discovery.md

**Comment by zet809** [comment]
Hi, @whowutwut , thx a lot, looks good to me for internal using. I will update it quickly and link it to 2.13.5 pre-release notes.

**Comment by whowutwut** [comment]
Closing, info is being tracked in the above URL.
