### ISSUE TITLE
Support public repo for xcat-dep in xcat.org

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat.org#64]
Creating a epic to track this work. Stage in the function as we find time.  

If we support the same concept as xcat-core for public repos... the following is true. 
1) support the latest release version of a branch 
2) Support the latest snap build of a branch 
3) Support the devel build 

If we apply this to xcat-dep repos.... Proposed the following URL for Linux... (debian would need to follow suit): 
* `repos/yum/devel/xcat-dep`  <--- devel build of xcat-dep
At this time, 2.13.4 is the currently release....
* `repos/yum/2.13/dep/dep-snap` <-- 2.13.5 devel xcat-dep , or the same as 2.13.4? 
* `repos/yum/2.13/dep/xcat-dep` <--- 2.13.4 GA xcat-dep

If we do not create a build for devel of a branch, then we need to fall back on the 2.13.4...  This seems to indicate a lot of complexity so maybe it's why we never did this in the first place :-)  ha ha..  

Some initial task breakdown...

* Manually create the repo for previous release 
* Create automation scripts that allow us to have a xcat-dep/devel version when we build xcat-dep code 
* Modify the promote script to adjust the repo from the latest devel to the release version

**Comment by daniceexi** [comment]
This is a legacy problem, thanks to start working on it.

**Comment by neo954** [comment]
The xcat.org was manually updated in the shape below.

* I put `xcat-dep` in the same level of directory as `xcat-core`. Regardless of it is in `devel` or `latest` or `2.13` or `2.12`. No extra `dep` directory. I think in this way, we can make things simple and clear. With some kind of consistency.
* As we discussed in the scramble meeting yesterday in Beijing, I think we can just ignore 2.13.4, as we are close to the release date of 2.13.5. Thus, the `xcat-dep` under `2.13` is just the latest one.
* Under `latest`, the `xcat-dep` is a symbolic link.
* I replaced the top-level `xcat-dep` to a symbolic link to `latest/xcat-dep`. In order to maintain some kind of backward compatible. It makes all existing yum/apt repository settings keep working.

    $ find repos -maxdepth 3 '(' -type d -o -type l ')' -ls | awk '{ print substr($0, index($0,$11)) }'
    repos
    repos/apt
    repos/apt/latest
    repos/apt/latest/xcat-dep -> ../2.13/xcat-dep
    repos/apt/latest/xcat-core
    repos/apt/2.12
    repos/apt/2.12/xcat-dep
    repos/apt/2.12/core-snap
    repos/apt/2.12/xcat-core
    repos/apt/xcat-dep -> latest/xcat-dep
    repos/apt/2.11
    repos/apt/2.11/xcat-dep
    repos/apt/2.11/core-snap
    repos/apt/2.11/xcat-core
    repos/apt/devel
    repos/apt/devel/xcat-dep
    repos/apt/devel/core-snap
    repos/apt/2.13.nodeset_performance
    repos/apt/2.13.nodeset_performance/xcat-dep -> ../2.13/xcat-dep
    repos/apt/2.13.nodeset_performance/core-snap
    repos/apt/2.13
    repos/apt/2.13/xcat-dep
    repos/apt/2.13/core-snap
    repos/apt/2.13/xcat-core
    repos/apt/2.10
    repos/apt/2.10/xcat-dep
    repos/apt/2.10/core-snap
    repos/apt/2.10/xcat-core
    repos/apt/2.13.perfopt
    repos/apt/2.13.perfopt/xcat-dep -> ../2.13/xcat-dep
    repos/apt/2.13.perfopt/core-snap
    repos/yum
    repos/yum/latest
    repos/yum/latest/xcat-dep -> ../2.13/xcat-dep
    repos/yum/latest/xcat-core
    repos/yum/2.12
    repos/yum/2.12/xcat-dep
    repos/yum/2.12/core-snap
    repos/yum/2.12/xcat-core
    repos/yum/xcat-dep -> latest/xcat-dep
    repos/yum/2.11
    repos/yum/2.11/xcat-dep
    repos/yum/2.11/core-snap
    repos/yum/2.11/xcat-core
    repos/yum/devel
    repos/yum/devel/xcat-dep
    repos/yum/devel/core-snap
    repos/yum/2.13
    repos/yum/2.13/xcat-dep
    repos/yum/2.13/core-snap
    repos/yum/2.13/xcat-core
    repos/yum/2.10
    repos/yum/2.10/xcat-dep
    repos/yum/2.10/core-snap
    repos/yum/2.10/xcat-core
    repos/yum/2.13.perfopt
    repos/yum/2.13.perfopt/xcat-dep -> ../2.13/xcat-dep
    repos/yum/2.13.perfopt/core-snap

**Comment by daniceexi** [comment]
looks good. 👍
